load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//java_format/private:defs.bzl", "PALANTIR_JVM_FLAGS")

package(default_visibility = ["//visibility:private"])

java_library(
    name = "javaformat",
    srcs = [
        "PalantirFormatter.java",
        "PalantirJavaFormatMain.java",
        "WorkspaceRoots.java",
        "package-info.java",
    ],
    visibility = ["//java_format/private/javatests/org/realityforge/rules/palantirjavaformat:__pkg__"],
    runtime_deps = ["@rules_palantir_java_format_maven//:com_palantir_javaformat_palantir_java_format"],
    deps = [
        "@rules_palantir_java_format_maven//:com_palantir_javaformat_palantir_java_format_spi",
        "@rules_palantir_java_format_maven//:org_jspecify_jspecify",
    ],
)

java_binary(
    name = "java_format",
    jvm_flags = PALANTIR_JVM_FLAGS,
    main_class = "org.realityforge.rules.palantirjavaformat.PalantirJavaFormatMain",
    visibility = ["//:__pkg__"],
    runtime_deps = [":javaformat"],
)

java_library(
    name = "watcher",
    srcs = [
        "PalantirJavaFormatWatchMain.java",
        "PalantirJavaFormatWatcher.java",
    ],
    visibility = ["//java_format/private/javatests/org/realityforge/rules/palantirjavaformat:__pkg__"],
    deps = [
        ":javaformat",
        "@rules_palantir_java_format_maven//:com_palantir_javaformat_palantir_java_format_spi",
        "@rules_palantir_java_format_maven//:org_jspecify_jspecify",
    ],
)

java_binary(
    name = "java_format_watch",
    jvm_flags = PALANTIR_JVM_FLAGS,
    main_class = "org.realityforge.rules.palantirjavaformat.PalantirJavaFormatWatchMain",
    visibility = ["//:__pkg__"],
    runtime_deps = [":watcher"],
)

java_library(
    name = "worker",
    srcs = [
        "PalantirJavaFormatWorkerMain.java",
        "WorkerProtocol.java",
    ],
    visibility = ["//java_format/private/javatests/org/realityforge/rules/palantirjavaformat:__pkg__"],
    deps = [
        ":javaformat",
        "@rules_palantir_java_format_maven//:com_palantir_javaformat_palantir_java_format_spi",
        "@rules_palantir_java_format_maven//:org_jspecify_jspecify",
    ],
)

java_binary(
    name = "palantir_java_format_worker",
    jvm_flags = PALANTIR_JVM_FLAGS,
    main_class = "org.realityforge.rules.palantirjavaformat.PalantirJavaFormatWorkerMain",
    visibility = ["//java_format/private:__pkg__"],
    runtime_deps = [":worker"],
)
